apiVersion: batch/v1
kind: Job
metadata:
  name: ballsbouncing-job
spec:
  template:
    spec:
      containers:
      - name: ballsbouncing-job
        image: yash5090/ballsbouncing:latest
        ports:
        - containerPort: 5000
      restartPolicy: OnFailure
