apiVersion: v1
kind: Service
metadata:
  name: ballsbouncing-service
spec:
  selector:
    app: ballsbouncing
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
